### ISSUE TITLE
separate example from udibo base code

### ISSUE THREAD

**Issue by elycheikhsmail** [udibo/react_app#66]
This will make easy to clone, run and understand

**Comment by KyleJune** [comment]
There are 3 examples in different repositories that can easily be forked. They are linked to in the README.md. One is a very basic example, another shows how you can use tailwindcss v3 in your project and another shows how you can use react query. Are you looking for anything other types of examples?

https://github.com/udibo/react_app#examples

The one example in this repository's example folder is mainly there for manually testing that various features for this framework are working correctly while developing it. It can also be used as a reference.

I plan on adding more detailed documentation to udibo.com. But until then, all there is available is the README.md and examples. If anything is unclear or not documented well, I can try updating them to be better.

https://github.com/udibo/react_app/issues/13
